name: Shared Flutter Quality and Security

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flutter-quality-and-security:
    uses: TomasThrawat/hyouka-flutter-workflows/.github/workflows/flutter-ci.yml@v1.1.0
    with:
      run-analyze: true
      run-tests: true
      check-format: false
      build-apk: false
      run-emulator-tests: false
      run-security-audit: true
      fail-on-security-findings: false
